# GitHub Pages / Jekyll Minimal theme configuration

title: German W Aparicio Jr
description: CV and Data Science Work Samples
url: "https://gaparicio.github.io"
baseurl: ""

author:
  name: German W Aparicio Jr

theme: jekyll-theme-minimal
show_downloads: false

# Defaults
# - use Minimal's `default` layout for site pages
# - use Minimal's `post` layout for blog entries
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
